# Generated by Django 4.0 on 2024-01-13 18:36

import app.models.manager
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone', models.CharField(blank=True, default='', max_length=225, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=225)),
                ('last_name', models.CharField(blank=True, default='', max_length=225)),
                ('user_type', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('delete', models.BooleanField(default=False)),
                ('user_id', models.CharField(blank=True, default='', max_length=225, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=1)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('NONE', 'NONE')], default='NONE', max_length=20)),
                ('blood_group', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'O+'), ('6', 'O-'), ('NONE', 'NONE')], default='NONE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', app.models.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('collection_point_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('slot_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('accepted', 'accepted'), ('pending', 'pending'), ('cancel', 'cancel')], default='pending', max_length=20)),
                ('optional_phone', models.CharField(blank=True, default='', max_length=225)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('lattitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('customer_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='WasteCollectionRecord',
            fields=[
                ('record_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('pending', 'pending'), ('cancel', 'cancel')], default='pending', max_length=20)),
                ('payment_status', models.CharField(default='failed', max_length=20)),
                ('collection_point_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.collectionpoint')),
            ],
        ),
        migrations.CreateModel(
            name='WasteTypeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('plastic', 'plastic'), ('iron', 'iron'), ('glass', 'glass'), ('paper', 'paper')], default='plastic', max_length=20)),
                ('quantity_collected', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('record_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wastecollectionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='WasteCollector',
            fields=[
                ('waste_collector_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('district_level', models.CharField(blank=True, choices=[('Dhanbad', 'Dhanbad'), ('Bokaro', 'Bokaro'), ('None', 'None')], max_length=20, null=True, unique=True)),
                ('user_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25)),
                ('payment_id', models.CharField(max_length=25)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_transactions', models.PositiveIntegerField(default=0)),
                ('debit_transactions', models.PositiveIntegerField(default=0)),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='StatePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_waste_collector_id', models.CharField(max_length=25, unique=True)),
                ('state_level', models.CharField(blank=True, choices=[('JHARKHAND', 'JHARKHAND'), ('WB', 'WB'), ('None', 'None')], max_length=20, null=True, unique=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('user_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('saved_address_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('lattitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('customer_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('user', 'user'), ('wc', 'wc')], default='user', max_length=20)),
                ('reason', models.CharField(default='none', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('canceled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('waste_collection_point_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collectionpoint')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_waste_collector_id', models.CharField(max_length=25, unique=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('district_level', models.CharField(blank=True, choices=[('Dhanbad', 'Dhanbad'), ('Bokaro', 'Bokaro'), ('None', 'None')], max_length=20, null=True, unique=True)),
                ('user_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='waste_collector_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.wastecollector'),
        ),
    ]
