# Generated by Django 4.0 on 2024-01-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_wastecollector_district_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtposition',
            name='state',
            field=models.CharField(blank=True, default='Jharkhand', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wastecollector',
            name='state',
            field=models.CharField(blank=True, default='Jharkhand', max_length=20, null=True),
        ),
    ]
